create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
create sequence sesion_seq start with 1 increment by 50;
create table sesion (presencial boolean, fin timestamp(6), id bigint not null, id_plan bigint, inicio timestamp(6), descripcion varchar(255), trabajo_realizado varchar(255), primary key (id));
create table sesion_datos_salud (sesion_id bigint not null, datos_salud varchar(255));
create table sesion_multimedia (sesion_id bigint not null, multimedia varchar(255));
alter table if exists sesion_datos_salud add constraint FKsuv6hr652pkc6f9yyygyeuy18 foreign key (sesion_id) references sesion;
alter table if exists sesion_multimedia add constraint FKqw93cgvsw1chd09u7ybcp54y9 foreign key (sesion_id) references sesion;
